<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Customer;
use AppBundle\Entity\Order;
use AppBundle\Helper\Traits\RepositoryOrdeByTrait;
use AppBundle\Helper\Traits\RepositoryPaginationTrait;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository  extends EntityRepository
{
    use RepositoryPaginationTrait;
    use RepositoryOrdeByTrait;

    /**
     * @param Customer $customer
     * @param array|null $orderBy
     * @param null $limit
     * @param int $offset
     * @return Order[]
     */
    public function findOrders(Customer $customer, array $orderBy = null, $limit = null, $offset = 0)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('o')
            ->from('AppBundle:Order', 'o')
            ->join('o.customer','c')
            ->where('c.id = :customerId')
            ->setParameter('customerId',$customer->getId())
        ;
        $this->initOrderBy($query, $orderBy);
        $this->initPagination($query, $limit, $offset);
        return $query->getQuery()->getResult();

    }

    /**
     * @param $id
     * @return Order
     * @throws NonUniqueResultException
     */
    public function findOrderById($id)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('o')
            ->from('AppBundle:Order', 'o')
            ->where('o.id=:id')
            ->setParameter('id',$id)
        ;
        return $query->getQuery()->getOneOrNullResult();
    }

    /**
     * @param Customer $customer
     * @return int
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function countOrder(Customer $customer){
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('COUNT(o.id)')
            ->from('AppBundle:Order', 'o')
            ->join('o.customer','c')
            ->where('c.id = :customerId')
            ->setParameter('customerId',$customer->getId())
        ;

        return $query->getQuery()->getSingleScalarResult();
    }
}
