<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Ordering;
use AppBundle\Helper\Traits\RepositoryOrdeByTrait;
use AppBundle\Helper\Traits\RepositoryPaginationTrait;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * OrderingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderingRepository  extends EntityRepository
{
    use RepositoryPaginationTrait;
    use RepositoryOrdeByTrait;

    /**
     * @param array|null $orderBy
     * @param null $limit
     * @param int $offset
     * @return mixed
     */
    public function findOrderings(array $orderBy = null, $limit = null, $offset = 0)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('o')
            ->from('AppBundle:Ordering', 'o')
        ;
        $this->initOrderBy($query, $orderBy);
        $this->initPagination($query, $limit, $offset);
        return $query->getQuery()->getResult();

    }

    /**
     * @param $id
     * @return Ordering
     * @throws NonUniqueResultException
     */
    public function findOrderingById($id)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('o')
            ->from('AppBundle:Ordering', 'o')
            ->where('o.id=:id')
            ->setParameter('id',$id)
        ;
        return $query->getQuery()->getOneOrNullResult();
    }
    /**
     * @param $id
     * @return Ordering
     * @throws NonUniqueResultException
     */
    public function orderingDiscounts($id)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('o','od')
            ->from('AppBundle:Ordering', 'o')
            ->leftJoin('o.orderDiscount','od')
            ->where('o.id=:id')
            ->setParameter('id',$id)
        ;
        return $query->getQuery()->getOneOrNullResult();
    }

    /**
     * @return int
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function countOrdering(){
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('COUNT(o.id)')
            ->from('AppBundle:Ordering', 'o')
        ;

        return $query->getQuery()->getSingleScalarResult();
    }
}
