services:
    app.account_manager:
        class: AppBundle\Manager\AccountManager
        arguments:
            - "@doctrine.orm.entity_manager"
    app.order_manager:
        class: AppBundle\Manager\OrderManager
        arguments:
            - "@doctrine.orm.entity_manager"
    app.product_manager:
        class: AppBundle\Manager\ProductManager
        arguments:
            - "@doctrine.orm.entity_manager"